name: emodebug
description: Emoji based semantic debuging. Debug the state and execution flow of a program with familiar idioms
homepage: https://github.com/synw/emodebug
version: 0.3.0

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  pedantic: ^1.8.0
  extra_pedantic: ^1.1.1+3
